import { Calendar, Filter, Heart, MessageCircle, Plus, Search, ShoppingCart, Trash2 } from 'lucide-react';
import { type FormEvent, useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import frameClassicImage from '@/assets/marketplace/frame-classic.svg';
import contactLensImage from '@/assets/marketplace/contact-lens.svg';
import eyeDropsImage from '@/assets/marketplace/eye-drops.svg';
import eyeVitaminImage from '@/assets/marketplace/eye-vitamin.svg';
import clinicCheckupImage from '@/assets/marketplace/clinic-checkup.svg';
import type { CartItem, FilterCategory, PriceFilter, Product, Service } from './types';

const STORAGE = { cart: 'mp_cart', orders: 'mp_orders', bookings: 'mp_bookings', points: 'mp_points', voucher: 'mp_voucher' };
const adminWhatsapp = '+6281234567890';
const formatRupiah = (v: number) => new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(v);
const products: Product[] = [
  { id: 'p1', name: 'Kacamata Prime Classic', category: 'kacamata', description: 'Frame ringan untuk harian.', price: 650000, image: frameClassicImage, badge: 'Best Seller', stock: 15, promo: true },
  { id: 'p2', name: 'Lensa Kontak Harian', category: 'lensa-kontak', description: '30 lensa steril nyaman.', price: 85000, image: contactLensImage, badge: 'Nyaman', stock: 35 },
  { id: 'p3', name: 'Tetes Mata Lubricant', category: 'tetes-mata', description: 'Membantu mata kering.', price: 55000, image: eyeDropsImage, badge: 'Original', stock: 20, requiresDoctorRecommendation: true },
  { id: 'p4', name: 'Vitamin Mata Prime', category: 'vitamin', description: 'Suplemen 30 kapsul.', price: 95000, image: eyeVitaminImage, badge: 'Rekomendasi', stock: 18, requiresDoctorRecommendation: true },
];
const services: Service[] = [
  { id: 's1', name: 'Paket Pemeriksaan Mata Lengkap', description: 'Cek mata menyeluruh.', duration: '60 menit', price: 150000, type: 'clinic-service' },
  { id: 's2', name: 'Paket Konsultasi Dokter Mata', description: 'Diskusi keluhan mata.', duration: '30 menit', price: 200000, type: 'clinic-service' },
  { id: 's3', name: 'Screening Mata Awal', description: 'Pemeriksaan dasar cepat.', duration: '20 menit', price: 75000, type: 'clinic-service' },
  { id: 's4', name: 'Pemeriksaan Minus / Silinder', description: 'Cek refraksi dan resep.', duration: '30 menit', price: 100000, type: 'clinic-service' },
];

export function MarketplacePage() {
  const navigate = useNavigate();
  const [search, setSearch] = useState(''); const [category, setCategory] = useState<FilterCategory>('semua'); const [priceFilter, setPriceFilter] = useState<PriceFilter>('none');
  const [cart, setCart] = useState<CartItem[]>([]); const [wishlist, setWishlist] = useState<string[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const [toast, setToast] = useState(''); const [points, setPoints] = useState(120); const [voucher, setVoucher] = useState<string | null>(null);
  const [productModal, setProductModal] = useState<Product | null>(null); const [cartOpen, setCartOpen] = useState(false); const [filterOpen, setFilterOpen] = useState(false);
  const [promoOpen, setPromoOpen] = useState(false); const [checkoutOpen, setCheckoutOpen] = useState(false); const [bookingService, setBookingService] = useState<Service | null>(null);

  useEffect(() => { setTimeout(() => setLoading(false), 500); try { setCart(JSON.parse(localStorage.getItem(STORAGE.cart) || '[]')); setPoints(Number(localStorage.getItem(STORAGE.points) || 120)); setVoucher(JSON.parse(localStorage.getItem(STORAGE.voucher) || 'null')); } catch { setError('Data marketplace gagal dimuat.'); } }, []);
  useEffect(() => localStorage.setItem(STORAGE.cart, JSON.stringify(cart)), [cart]); useEffect(() => localStorage.setItem(STORAGE.points, String(points)), [points]); useEffect(() => localStorage.setItem(STORAGE.voucher, JSON.stringify(voucher)), [voucher]);
  useEffect(() => { if (!toast) return; const t = setTimeout(() => setToast(''), 2200); return () => clearTimeout(t); }, [toast]);

  const matchText = (v: string) => v.toLowerCase().includes(search.toLowerCase());
  const filteredProducts = useMemo(() => {
    let items = products.filter((p) => !search || matchText(`${p.name} ${p.description} ${p.category}`));
    if (category === 'kacamata' || category === 'lensa-kontak' || category === 'tetes-mata' || category === 'vitamin') items = items.filter((p) => p.category === category);
    if (category === 'rekomendasi-dokter') items = items.filter((p) => p.requiresDoctorRecommendation);
    if (category === 'promo') items = items.filter((p) => p.promo);
    if (priceFilter === 'under-100k') items = items.filter((p) => p.price < 100000); if (priceFilter === '100k-250k') items = items.filter((p) => p.price >= 100000 && p.price <= 250000); if (priceFilter === 'above-250k') items = items.filter((p) => p.price > 250000);
    if (priceFilter === 'lowest') items = [...items].sort((a, b) => a.price - b.price); if (priceFilter === 'highest') items = [...items].sort((a, b) => b.price - a.price);
    return items;
  }, [search, category, priceFilter]);
  const filteredServices = useMemo(() => services.filter((s) => (!search || matchText(`${s.name} ${s.description}`)) && (category === 'semua' || category === 'layanan-klinik')), [search, category]);
  const subtotal = cart.reduce((t, i) => t + i.price * i.quantity, 0); const discount = voucher === 'PRIME10' ? Math.round(subtotal * 0.1) : voucher === 'PRIME25K' ? 25000 : 0;

  const addToCart = (i: Omit<CartItem, 'quantity'>) => { setCart((c) => c.some((x) => x.id === i.id) ? c.map((x) => x.id === i.id ? { ...x, quantity: x.quantity + 1 } : x) : [...c, { ...i, quantity: 1 }]); setToast('Produk ditambahkan ke keranjang.'); };
  const bookService = (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); localStorage.setItem(STORAGE.bookings, JSON.stringify([...(JSON.parse(localStorage.getItem(STORAGE.bookings) || '[]')), { at: Date.now(), service: bookingService?.name }])); setBookingService(null); setToast('Booking berhasil dibuat.'); };
  if (loading) return <div className="rounded-3xl bg-white p-4">Memuat marketplace...</div>; if (error) return <div className="rounded-3xl bg-red-50 p-4 text-red-700">{error}</div>;

  return <section className="space-y-4 pb-[120px]">
    <header className="rounded-3xl bg-white p-4 shadow-prime-card"><div className="flex items-start justify-between"><div><h1 className="text-2xl font-bold">Marketplace</h1><p className="text-sm text-prime-muted">Fokus belanja kebutuhan mata dengan produk dan layanan klinik.</p></div><button aria-label="Buka keranjang" onClick={() => setCartOpen(true)} className="h-11 w-11 rounded-xl border"><ShoppingCart className="mx-auto mt-2"/></button></div></header>
    <div className="flex gap-2"><label className="flex min-h-[44px] flex-1 items-center gap-2 rounded-2xl bg-white px-3"><Search className="h-4 w-4"/><input value={search} onChange={(e) => setSearch(e.target.value)} className="w-full bg-transparent" placeholder="Cari produk/layanan"/></label><button aria-label="Buka filter" onClick={() => setFilterOpen(true)} className="h-11 w-11 rounded-xl bg-white"><Filter className="mx-auto mt-2"/></button></div>
    <button onClick={() => document.getElementById('rekomendasi')?.scrollIntoView({ behavior: 'smooth' })} className="w-full rounded-3xl bg-gradient-to-r from-[#b19731] to-[#f8df9a] p-4 text-left"><p className="font-bold">Etalase kebutuhan mata Prime</p><p className="text-sm">Produk tepercaya dan layanan klinik untuk kesehatan mata Anda.</p><span className="text-xs underline">Lihat Rekomendasi</span></button>
    <div className="marketplace-scrollbar-hide flex gap-2 overflow-x-auto pb-1">{['semua','kacamata','lensa-kontak','tetes-mata','vitamin','layanan-klinik','promo'].map((c)=><button key={c} onClick={()=>setCategory(c as FilterCategory)} className={`min-h-[44px] shrink-0 rounded-full px-4 ${category===c?'bg-prime-gold text-white':'bg-white'}`}>{c}</button>)}</div>
    <section id="rekomendasi" className="space-y-2"><h2 className="font-bold">Produk Pilihan</h2><div className="grid grid-cols-2 gap-3">{filteredProducts.map((p)=><article key={p.id} className="rounded-2xl bg-white p-2"><button onClick={()=>setProductModal(p)} className="text-left"><img src={p.image} className="h-24 w-full"/><p className="text-xs">{p.badge}</p><p className="text-sm font-semibold">{p.name}</p><p className="text-xs">{p.description}</p></button><div className="mt-2 flex items-center justify-between"><p className="text-sm font-bold">{formatRupiah(p.price)}</p><div className="flex gap-1"><button aria-label="wishlist" onClick={()=>{setWishlist((w)=>w.includes(p.id)?w.filter((x)=>x!==p.id):[...w,p.id]); setToast('Ditambahkan ke wishlist.');}}><Heart className={`h-4 w-4 ${wishlist.includes(p.id)?'fill-rose-500 text-rose-500':''}`}/></button><button aria-label="Tambah ke keranjang" onClick={()=>addToCart({ id:p.id,itemType:'product',name:p.name,price:p.price})}><Plus className="h-4 w-4"/></button></div></div></article>)}</div>{filteredProducts.length===0 && <p className="rounded-2xl bg-white p-4 text-sm">Produk atau layanan tidak ditemukan.</p>}</section>
    <section className="space-y-2"><h2 className="font-bold">Layanan Klinik</h2>{filteredServices.map((s)=><article key={s.id} className="rounded-2xl bg-white p-3"><p className="font-semibold">{s.name}</p><p className="text-xs">{s.description} • {s.duration}</p><div className="mt-2 flex items-center justify-between"><p>{formatRupiah(s.price)}</p><button onClick={()=>setBookingService(s)} className="prime-cta-gold px-3">Booking</button></div></article>)}</section>
    <section className="rounded-2xl bg-white p-4"><p className="font-semibold">Poin saat ini: {points}</p><p className="text-xs">Progress voucher berikutnya {Math.min(points, 200)}/200</p><button onClick={()=>{ if(points<40)return setToast('Poin belum cukup untuk voucher ini.'); setPoints((p)=>p-40); setVoucher('PRIME10'); setToast('Voucher berhasil ditukar.');}} className="mt-2 rounded bg-prime-gold px-3 py-2 text-white">Tukar Sekarang</button></section>
    <section className="rounded-2xl bg-white p-4"><button onClick={()=>setPromoOpen(true)} className="rounded bg-prime-gold-soft px-3 py-2">Lihat Promo</button></section>
    <section className="grid grid-cols-2 gap-2">{['Produk Original','Rekomendasi Dokter','Booking Mudah','Reward & Voucher'].map((x)=><div key={x} className="rounded-2xl bg-white p-3 text-xs"><p className="font-semibold">{x}</p></div>)}</section>
    <button onClick={()=>window.open(`https://wa.me/${adminWhatsapp.replace(/\D/g,'')}`,'_blank')} className="min-h-[44px] w-full rounded-2xl bg-prime-teal-soft"><MessageCircle className="mr-1 inline h-4"/>Hubungi Admin</button>

    {cartOpen && <div className="fixed inset-0 z-50 bg-black/30 p-4" onClick={()=>setCartOpen(false)}><div className="mx-auto mt-20 max-w-sm rounded-2xl bg-white p-4" onClick={(e)=>e.stopPropagation()}><p className="font-bold">Keranjang</p>{cart.length===0?<p className="text-sm">Keranjang masih kosong. Tambahkan produk atau layanan terlebih dahulu.</p>:cart.map((i)=><div key={i.id} className="mt-2 flex items-center justify-between"><p className="text-xs">{i.name}</p><div><button onClick={()=>setCart((c)=>c.map((x)=>x.id===i.id?{...x,quantity:Math.max(1,x.quantity-1)}:x))}>-</button><span className="px-2">{i.quantity}</span><button onClick={()=>setCart((c)=>c.map((x)=>x.id===i.id?{...x,quantity:x.quantity+1}:x))}>+</button><button onClick={()=>setCart((c)=>c.filter((x)=>x.id!==i.id))}><Trash2 className="inline h-4"/></button></div></div>)}<p className="mt-3">Subtotal: {formatRupiah(subtotal)}</p><p>Total: {formatRupiah(Math.max(0,subtotal-discount))}</p><button disabled={!cart.length} onClick={()=>setCheckoutOpen(true)} className="prime-cta-gold mt-2 w-full">Checkout</button></div></div>}
    {productModal && <div className="fixed inset-0 z-50 bg-black/30 p-4" onClick={()=>setProductModal(null)}><div className="mx-auto mt-16 max-w-sm rounded-2xl bg-white p-4" onClick={(e)=>e.stopPropagation()}><img src={productModal.image} className="h-28 w-full"/><p className="font-bold">{productModal.name}</p><p>{formatRupiah(productModal.price)}</p><p className="text-xs">Stok {productModal.stock}</p>{(productModal.category==='tetes-mata'||productModal.category==='vitamin')&&<p className="text-xs">Gunakan sesuai petunjuk. Konsultasikan ke dokter jika keluhan menetap.</p>}<button className="prime-cta-gold mt-2 w-full" onClick={()=>{addToCart({id:productModal.id,itemType:'product',name:productModal.name,price:productModal.price}); setProductModal(null);}}>Tambah ke keranjang</button></div></div>}
    {filterOpen && <div className="fixed inset-0 z-50 bg-black/30 p-4" onClick={()=>setFilterOpen(false)}><div className="mx-auto mt-20 max-w-sm rounded-2xl bg-white p-4" onClick={(e)=>e.stopPropagation()}><p className="font-bold">Filter Marketplace</p><select className="mt-2 w-full border" value={category} onChange={(e)=>setCategory(e.target.value as FilterCategory)}><option value="semua">Semua</option><option value="kacamata">Kacamata</option><option value="lensa-kontak">Lensa Kontak</option><option value="tetes-mata">Tetes Mata</option><option value="vitamin">Vitamin</option><option value="layanan-klinik">Layanan Klinik</option><option value="rekomendasi-dokter">Rekomendasi Dokter</option><option value="promo">Promo</option></select><select className="mt-2 w-full border" value={priceFilter} onChange={(e)=>setPriceFilter(e.target.value as PriceFilter)}><option value="none">Semua Harga</option><option value="lowest">Terendah</option><option value="highest">Tertinggi</option><option value="under-100k">Di bawah Rp100.000</option><option value="100k-250k">Rp100.000–Rp250.000</option><option value="above-250k">Di atas Rp250.000</option></select><div className="mt-2 flex gap-2"><button onClick={()=>setFilterOpen(false)} className="prime-cta-gold flex-1">Terapkan Filter</button><button onClick={()=>{setCategory('semua');setPriceFilter('none');}} className="flex-1 rounded border">Reset Filter</button></div></div></div>}
    {promoOpen && <div className="fixed inset-0 z-50 bg-black/30 p-4" onClick={()=>setPromoOpen(false)}><div className="mx-auto mt-20 max-w-sm rounded-2xl bg-white p-4" onClick={(e)=>e.stopPropagation()}><p className="font-bold">Promo Hari Ini</p><p className="text-sm">Diskon 10% produk tertentu</p><p className="text-sm">Diskon 25K layanan tertentu</p><button onClick={()=>{if(!cart.length){setToast('Tambahkan produk dulu untuk menggunakan promo.');return;} setVoucher('PRIME10'); setToast('Promo diterapkan.'); setPromoOpen(false);}} className="mt-2 rounded bg-prime-gold px-3 py-2 text-white">Gunakan Promo</button></div></div>}
    {checkoutOpen && <div className="fixed inset-0 z-50 bg-black/30 p-4" onClick={()=>setCheckoutOpen(false)}><form className="mx-auto mt-20 max-w-sm rounded-2xl bg-white p-4" onClick={(e)=>e.stopPropagation()} onSubmit={(e)=>{e.preventDefault(); localStorage.setItem(STORAGE.orders, JSON.stringify([...(JSON.parse(localStorage.getItem(STORAGE.orders)||'[]')),{at:Date.now(),items:cart}])); setCart([]); setCheckoutOpen(false); setCartOpen(false); setToast('Pesanan berhasil dikirim.');}}><p className="font-bold">Checkout</p><p className="text-xs">Total {formatRupiah(Math.max(0,subtotal-discount))}</p><input required placeholder="Nama pasien" className="mt-2 w-full rounded border p-2"/><input required placeholder="Nomor WhatsApp" className="mt-2 w-full rounded border p-2"/><select className="mt-2 w-full rounded border p-2"><option>Ambil di klinik</option><option>Konsultasi dulu</option></select><button className="prime-cta-gold mt-2 w-full">Kirim pesanan</button></form></div>}
    {bookingService && <div className="fixed inset-0 z-50 bg-black/30 p-4" onClick={()=>setBookingService(null)}><form onSubmit={bookService} className="mx-auto mt-20 max-w-sm rounded-2xl bg-white p-4" onClick={(e)=>e.stopPropagation()}><p className="font-bold">Booking Layanan</p><input readOnly value={bookingService.name} className="mt-2 w-full rounded border p-2"/><input required type="date" className="mt-2 w-full rounded border p-2"/><input required type="time" className="mt-2 w-full rounded border p-2"/><input required placeholder="Keluhan singkat" className="mt-2 w-full rounded border p-2"/><input required placeholder="WhatsApp" className="mt-2 w-full rounded border p-2"/><button className="prime-cta-gold mt-2 w-full">Konfirmasi booking</button><button type="button" onClick={()=>navigate('/laporan')} className="mt-2 w-full rounded border p-2"><Calendar className="mr-1 inline h-4"/>Lihat Jadwal</button></form></div>}
    {toast && <div className="fixed left-1/2 top-4 z-[70] -translate-x-1/2 rounded bg-prime-black px-3 py-2 text-xs text-white">{toast}</div>}
  </section>;
}
