import { Bell, BookOpenText, Brain, CalendarCheck2, CheckCircle2, ChevronRight, Clock3, Eye, FileText, Glasses, HeartPulse, ShieldCheck, Sparkles, Stethoscope } from 'lucide-react';
import { LucideIcon } from 'lucide-react';

export function LoadingSkeleton() {
  return <div className="h-24 animate-pulse rounded-prime-xl bg-prime-line/60" />;
}

export function EmptyState({ title, description }: { title: string; description: string }) {
  return <div className="rounded-prime-xl border border-dashed border-prime-line bg-white px-4 py-5 text-center text-prime-muted"><p className="font-bold text-prime-ink">{title}</p><p className="mt-1 text-sm">{description}</p></div>;
}

export function AppModal({ open, title, children, onClose }: { open: boolean; title: string; children: React.ReactNode; onClose: () => void }) {
  if (!open) return null;
  return <div className="fixed inset-0 z-[1200] flex items-center justify-center bg-black/40 px-4" onClick={onClose}><div className="w-full max-w-sm rounded-prime-xl bg-white p-5 shadow-2xl" onClick={(e) => e.stopPropagation()}><h3 className="text-lg font-extrabold text-prime-ink">{title}</h3><div className="mt-3 text-sm text-prime-muted">{children}</div><button type="button" onClick={onClose} className="prime-cta-dark mt-4 w-full">Tutup</button></div></div>;
}

export function Toast({ message }: { message: string }) { return <p className="rounded-xl border border-prime-teal/25 bg-prime-teal-soft px-4 py-3 text-sm font-bold text-prime-ink">{message}</p>; }

export function HomeHeader({ onNotification }: { onNotification: () => void }) {
  return <header className="rounded-prime-xl border border-prime-line bg-white px-4 py-4 shadow-prime-card"><div className="flex items-start justify-between"><div><p className="text-[28px] font-extrabold leading-none tracking-tight text-prime-gold-dark">PRIME</p><p className="text-xs font-semibold text-prime-muted">Klinik Utama Mata</p></div><button type="button" onClick={onNotification} aria-label="Notifikasi" className="notification-button inline-flex h-11 w-11 items-center justify-center rounded-full border border-prime-line bg-white text-prime-gold"><Bell className="h-5 w-5" /></button></div><div className="mt-4"><h1 className="text-[24px] font-extrabold text-prime-ink">Halo, Pasien 👋</h1><p className="text-sm text-prime-muted">Pantau kesehatan mata Anda dengan cepat hari ini.</p></div></header>;
}

export function SummaryCard({ onSummary, onReminder }: { onSummary: () => void; onReminder: () => void }) { return <article className="rounded-prime-xl border border-prime-line bg-white p-4 shadow-prime-card"><span className="inline-flex items-center gap-1 rounded-full bg-prime-gold-soft px-3 py-1 text-xs font-bold text-prime-gold-dark"><Sparkles className="h-3.5 w-3.5" /> Ringkasan Hari Ini</span><h2 className="mt-3 text-xl font-extrabold text-prime-ink">Kesehatan mata Anda dalam satu tampilan.</h2><p className="mt-1 text-sm text-prime-muted">Lihat antrean, jadwal, dan langkah perawatan singkat.</p><button onClick={onSummary} type="button" className="prime-link-cta mt-2 inline-flex items-center gap-1 text-sm font-bold text-prime-gold-dark">Lihat Ringkasan <ChevronRight className="h-4 w-4" /></button><div className="mt-4 rounded-xl border border-prime-line bg-prime-surface p-3"><p className="text-sm font-bold text-prime-ink">Pengingat 20-20-20</p><p className="text-xs text-prime-muted">Setiap 20 menit, lihat jauh 20 detik.</p><button type="button" onClick={onReminder} className="prime-cta-gold mt-2 w-full text-sm">Mulai Pengingat</button></div></article>; }

export function QuickActions({ onBooking, onAi }: { onBooking: () => void; onAi: () => void }) { return <section><h2 className="mb-3 text-lg font-extrabold text-prime-ink">Aksi Cepat</h2><div className="grid grid-cols-2 gap-3">{[{t:'Booking Pemeriksaan',d:'Pilih jadwal konsultasi.',i:CalendarCheck2,c:'prime-gold-card',on:onBooking},{t:'Cek AI Mata',d:'Skrining awal cepat.',i:Brain,c:'bg-white',on:onAi}].map(({t,d,i:Icon,c,on})=><button key={t} onClick={on} className={`prime-touch-feedback min-h-[148px] rounded-prime-lg border border-prime-line p-4 text-left ${c}`}><Icon className="h-5 w-5" /><p className="mt-2 font-extrabold">{t}</p><p className="text-xs opacity-90">{d}</p></button>)}</div></section>; }

export function QueueCard({ onDetail }: { onDetail: () => void }) { return <article className="rounded-prime-xl border border-prime-line bg-white p-4"><p className="text-xs font-extrabold uppercase tracking-widest text-prime-gold-dark">Antrean Hari Ini</p><p className="mt-2 text-3xl font-extrabold">A-017</p><p className="mt-2 inline-flex items-center gap-2 text-sm text-prime-muted"><Clock3 className="h-4 w-4 text-prime-teal"/> Estimasi ±15 menit</p><p className="mt-2 inline-flex items-center gap-1 rounded-full bg-prime-gold-soft px-2 py-1 text-xs font-bold text-prime-gold-dark"><CheckCircle2 className="h-3.5 w-3.5"/>Menunggu Pemeriksaan</p><button onClick={onDetail} className="prime-cta-dark mt-3 px-4 text-sm">Lihat Detail</button></article>; }

export function NextScheduleCard({ onDetail }: { onDetail: () => void }) { return <article className="rounded-prime-xl border border-prime-line bg-white p-4"><div className="flex justify-between"><div><p className="text-xs font-extrabold uppercase tracking-widest text-prime-gold-dark">Jadwal Berikutnya</p><p className="mt-2 font-extrabold text-prime-ink">dr. Sp.M</p><p className="text-sm text-prime-muted">4 Mei 2026 • 10.30 WIB</p><p className="text-sm font-semibold text-prime-ink">Pemeriksaan Mata Lengkap</p><p className="mt-1 text-xs font-bold text-prime-teal">Status: Booking Terkonfirmasi</p></div><Stethoscope className="h-6 w-6 text-prime-teal"/></div><button onClick={onDetail} className="prime-link-cta mt-2 inline-flex items-center gap-1 text-sm font-bold text-prime-gold-dark">Detail / Ubah Jadwal <ChevronRight className="h-4 w-4"/></button></article>; }

export function QuickMenu({ onClick }: { onClick: (path: string, title: string) => void }) { const items:{title:string;path:string;icon:LucideIcon}[]=[{title:'Riwayat Pemeriksaan',path:'/laporan',icon:FileText},{title:'Resep Kacamata',path:'/resep-kacamata',icon:Glasses},{title:'Hasil AI Mata',path:'/ai/history',icon:Eye},{title:'Edukasi Mata',path:'/edukasi',icon:BookOpenText}]; return <section className="rounded-prime-xl border border-prime-line bg-white p-4"><h2 className="text-lg font-extrabold">Menu Cepat</h2><div className="mt-3 grid grid-cols-2 gap-3">{items.map(({title,path,icon:Icon})=><button key={title} onClick={()=>onClick(path,title)} className="rounded-xl border border-prime-line bg-prime-surface p-3 text-left"><Icon className="h-4 w-4 text-prime-gold-dark"/><p className="mt-2 text-xs font-bold text-prime-ink">{title}</p></button>)}</div></section>; }

export function DailyWinsCard({ points, checkedIn, onCheckIn, onSeeAll }: { points: number; checkedIn: boolean; onCheckIn: () => void; onSeeAll: () => void }) { return <section className="rounded-prime-xl border border-prime-line bg-white p-4"><p className="text-xs font-extrabold uppercase tracking-widest text-prime-gold-dark">Daily Wins</p><p className="text-sm text-prime-muted">Poin hari ini: <span className="font-bold text-prime-ink">{points}</span></p><ul className="mt-2 list-disc pl-5 text-sm text-prime-ink"><li>Check-in harian</li><li>Baca tips mata</li><li>Selesaikan 20-20-20</li></ul><button disabled={checkedIn} onClick={onCheckIn} className="prime-cta-gold mt-3 w-full text-sm">{checkedIn ? 'Sudah check-in hari ini' : 'Check-in Harian +10 poin'}</button><button onClick={onSeeAll} className="prime-link-cta mt-2 inline-flex items-center gap-1 text-sm font-bold text-prime-gold-dark">Lihat Semua Misi <ChevronRight className="h-4 w-4"/></button></section>; }

export function EyeHealthTipCard({ onRead }: { onRead: () => void }) { return <section className="rounded-prime-xl border border-prime-line bg-white p-4"><div className="flex gap-3"><div className="rounded-xl bg-prime-gold-soft p-2"><ShieldCheck className="h-5 w-5 text-prime-gold-dark"/></div><div><p className="text-xs font-extrabold uppercase tracking-widest text-prime-gold-dark">Tips Kesehatan Mata</p><p className="text-sm font-bold text-prime-ink">Cara mencegah mata lelah akibat layar</p><p className="text-sm text-prime-muted">Atur pencahayaan, gunakan aturan 20-20-20, dan jaga jarak layar.</p><button onClick={onRead} className="prime-link-cta mt-1 inline-flex items-center gap-1 text-sm font-bold text-prime-gold-dark">Baca Selengkapnya <ChevronRight className="h-4 w-4"/></button></div></div></section>; }
