import { CheckCircle2, Coins, Flame, Gift, Medal, Trophy } from 'lucide-react';
import { useState } from 'react';
import { useGamificationStore } from './gamificationStore';

export function DailyWinsCard() {
  const [feedback, setFeedback] = useState('');
  const { user, getDailyMissions, checkInDaily, completeMission } = useGamificationStore();
  const missions = getDailyMissions(user.userId);
  return (
    <article className="rounded-3xl border border-cyan-100 bg-white p-4 shadow-sm shadow-cyan-50">
      <div className="flex items-center justify-between"><p className="text-sm font-semibold text-slate-900">Daily Wins</p><span className="text-xs text-cyan-700">{user.lastCheckInDate === new Date().toISOString().slice(0, 10) ? 'Sudah check-in hari ini' : 'Belum check-in hari ini'}</span></div>
      <div className="mt-2 flex items-center gap-4 text-sm"><span className="inline-flex items-center gap-1 text-cyan-700"><Flame size={14} />Streak {user.currentStreak} hari</span><span className="inline-flex items-center gap-1 text-amber-600"><Coins size={14} />{user.totalPoints} poin</span></div>
      <button onClick={() => { const result = checkInDaily(user.userId); setFeedback(result.message); setTimeout(() => setFeedback(''), 2200); }} className="mt-3 w-full rounded-2xl bg-cyan-600 px-3 py-2 text-sm font-semibold text-white transition hover:scale-[1.01]">Check-in Harian</button>
      {feedback && <p className="mt-2 text-xs text-cyan-700">{feedback}</p>}
      <div className="mt-3 space-y-2">{missions.map((mission) => <div key={mission.id} className="rounded-2xl bg-cyan-50/60 p-2.5"><div className="flex items-start justify-between gap-2"><div><p className="text-xs font-semibold text-slate-800">{mission.title}</p><p className="text-[11px] text-slate-500">{mission.description}</p></div><span className="text-[11px] font-semibold text-cyan-700">+{mission.pointReward}</span></div><button disabled={mission.isCompleted} onClick={() => { const result = completeMission(user.userId, mission.id); setFeedback(result.message); }} className="mt-2 rounded-xl bg-white px-2.5 py-1.5 text-[11px] font-medium text-cyan-700 disabled:opacity-60">{mission.isCompleted ? 'Selesai' : 'Selesaikan'}</button></div>)}</div>
    </article>
  );
}

export function BadgeSection() { const { badges } = useGamificationStore(); return <section className="rounded-[20px] bg-white p-4 shadow-md shadow-slate-200/70"><div className="flex items-center gap-2"><Medal size={16} className="text-cyan-700" /><h2 className="text-base font-semibold text-slate-900">Badge Achievement</h2></div><div className="mt-3 space-y-2">{badges.map((badge) => <article key={badge.id} className="rounded-xl border border-cyan-100 p-2.5"><div className="flex items-center justify-between"><p className="text-sm font-semibold">{badge.icon} {badge.name}</p><span className={`text-[11px] ${badge.isUnlocked ? 'text-emerald-600' : 'text-slate-400'}`}>{badge.isUnlocked ? 'Unlocked' : 'Locked'}</span></div><p className="text-xs text-slate-500">{badge.description}</p>{badge.unlockedAt && <p className="mt-1 text-[11px] text-cyan-700">Didapat: {new Date(badge.unlockedAt).toLocaleDateString('id-ID')}</p>}</article>)}</div></section>; }

export function RewardSection() { const { user, getAvailableRewards, redeemReward } = useGamificationStore(); const rewards = getAvailableRewards(user.userId); const next = rewards.find((r) => user.totalPoints < r.pointsRequired) ?? rewards[0]; const progress = Math.min(100, Math.round((user.totalPoints / next.pointsRequired) * 100)); return <section className="rounded-3xl border border-cyan-100 bg-white p-4 shadow-sm shadow-cyan-50"><div className="flex items-center gap-2"><Gift size={16} className="text-cyan-700" /><h3 className="text-sm font-semibold text-slate-900">Reward Poin</h3></div><div className="mt-2 h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-cyan-500" style={{ width: `${progress}%` }} /></div><p className="mt-1 text-[11px] text-slate-500">Progress ke reward berikutnya: {progress}%</p><div className="mt-3 space-y-2">{rewards.map((reward) => { const enough = user.totalPoints >= reward.pointsRequired; return <article key={reward.id} className="rounded-2xl bg-cyan-50/60 p-3"><div className="flex items-start justify-between gap-2"><div><p className="text-sm font-semibold text-slate-900">{reward.title}</p><p className="text-xs text-slate-500">{reward.description}</p><p className="mt-1 text-xs font-semibold text-cyan-700">{reward.pointsRequired} poin</p></div><Trophy className="text-cyan-600" size={16} /></div><button onClick={() => alert(redeemReward(user.userId, reward.id).message)} disabled={!enough} className="mt-2 rounded-xl bg-cyan-600 px-3 py-2 text-xs font-semibold text-white disabled:cursor-not-allowed disabled:bg-slate-300">{enough ? 'Tukar Poin' : 'Poin belum cukup'}</button></article>; })}</div></section>; }

export function PointsStreakCard() { const { user } = useGamificationStore(); return <article className="rounded-[20px] bg-white p-4 shadow-md shadow-slate-200/70"><div className="grid grid-cols-2 gap-2"><div className="rounded-xl bg-cyan-50 p-3"><p className="text-xs text-slate-500">Total Poin</p><p className="mt-1 inline-flex items-center gap-1 text-lg font-semibold text-cyan-700"><Coins size={16} />{user.totalPoints}</p></div><div className="rounded-xl bg-orange-50 p-3"><p className="text-xs text-slate-500">Streak Harian</p><p className="mt-1 inline-flex items-center gap-1 text-lg font-semibold text-amber-600"><Flame size={16} />{user.currentStreak} hari</p></div></div><p className="mt-3 text-xs text-slate-500 inline-flex items-center gap-1"><CheckCircle2 size={14} className="text-emerald-600" />Level {user.level} • Longest streak {user.longestStreak} hari</p></article>; }
