import { useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { zodResolver } from '@hookform/resolvers/zod';
import { Activity, CalendarCheck2, ChevronRight, CircleAlert, Download, Eye, Info, PhoneCall } from 'lucide-react';
import { Card, EmptyState, ErrorState, LoadingSkeleton, Modal, Toast } from './components/ui';
import type { DataTypeKey, ExaminationHistoryItem, LastAiResult, PatientReport, PeriodKey, PressureTrendItem, VisionTrendItem } from './components/reportTypes';

const periods: { key: PeriodKey; label: string }[] = [{ key: '1bulan', label: '1 Bulan' }, { key: '3bulan', label: '3 Bulan' }, { key: '6bulan', label: '6 Bulan' }, { key: '1tahun', label: '1 Tahun' }];
const dataTypes: { key: DataTypeKey; label: string }[] = [{ key: 'semua', label: 'Semua' }, { key: 'dokter', label: 'Pemeriksaan Dokter' }, { key: 'ai', label: 'AI Screening' }, { key: 'resep', label: 'Resep Kacamata' }];
const bookingSchema = z.object({ examType: z.string().min(1), date: z.string().min(1), time: z.string().min(1), complaint: z.string().min(3), whatsapp: z.string().min(9) });

const report: PatientReport = { patientName: 'Budi Santosa', medicalRecordNumber: 'RM-2026-00128', lastVisitDate: '2026-05-12', doctorName: 'dr. Sp.M', healthStatus: 'Perlu Pemantauan', rightVision: '6/9', leftVision: '6/12', intraocularPressure: 18, dryEyeRisk: 'Sedang' };
const visionByPeriod: Record<PeriodKey, VisionTrendItem[]> = { '1bulan': [{ month: 'Mei', date: '2026-05-12', rightEye: 9, leftEye: 6.2 }], '3bulan': [{ month: 'Mar', date: '2026-03-10', rightEye: 6, leftEye: 6 }, { month: 'Apr', date: '2026-04-20', rightEye: 6, leftEye: 6.5 }, { month: 'Mei', date: '2026-05-12', rightEye: 9, leftEye: 6.2 }], '6bulan': [{ month: 'Des', date: '2025-12-15', rightEye: 6.2, leftEye: 6.8 }, { month: 'Feb', date: '2026-02-08', rightEye: 6.3, leftEye: 6.4 }, { month: 'Mei', date: '2026-05-12', rightEye: 9, leftEye: 6.2 }], '1tahun': [] };
const pressureByPeriod: Record<PeriodKey, PressureTrendItem[]> = { '1bulan': [{ month: 'Mei', value: 18 }], '3bulan': [{ month: 'Mar', value: 21 }, { month: 'Apr', value: 19 }, { month: 'Mei', value: 18 }], '6bulan': [{ month: 'Des', value: 17 }, { month: 'Jan', value: 18 }, { month: 'Feb', value: 22 }, { month: 'Mar', value: 21 }, { month: 'Apr', value: 19 }, { month: 'Mei', value: 18 }], '1tahun': [] };
const history: ExaminationHistoryItem[] = [{ id: 'exam-001', date: '2026-05-12', title: 'Pemeriksaan Mata Lengkap', doctor: 'dr. Sp.M', status: 'Selesai', type: 'dokter', complaint: 'Mata buram dan mudah lelah', rightVision: '6/9', leftVision: '6/12', intraocularPressure: 18, diagnosis: 'Kelainan refraksi ringan mata kiri.', recommendation: 'Kontrol ulang 1 bulan lagi' }];
const lastAi: LastAiResult = { id: 'ai-001', date: '2026-03-10', riskLevel: 'Sedang', symptoms: ['Mata buram', 'Mata merah'], painLevel: 3, duration: '1-3 hari', summary: 'AI menyarankan pemeriksaan lanjutan jika keluhan menetap.', analysisReason: 'Pola gejala menunjukkan iritasi dan kelelahan mata.', recommendation: 'Kurangi screen time, gunakan pelumas mata, konsultasi dokter jika >3 hari.' };

export function LaporanPage() {
  const navigate = useNavigate();
  const [period, setPeriod] = useState<PeriodKey>('3bulan');
  const [dataType, setDataType] = useState<DataTypeKey>('semua');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [toast, setToast] = useState('');
  const [modal, setModal] = useState<string | null>(null);
  const [selected, setSelected] = useState<any>(null);
  const form = useForm<z.infer<typeof bookingSchema>>({ resolver: zodResolver(bookingSchema), defaultValues: { examType: 'Pemeriksaan Mata Lengkap' } });

  useEffect(() => { const t = setTimeout(() => setLoading(false), 700); return () => clearTimeout(t); }, []);
  useEffect(() => { if (!toast) return; const t = setTimeout(() => setToast(''), 2200); return () => clearTimeout(t); }, [toast]);

  const vision = visionByPeriod[period]; const pressure = pressureByPeriod[period];
  const filteredHistory = history.filter((h) => dataType === 'semua' || h.type === dataType);
  const filteredVision = dataType === 'resep' ? [] : vision;
  const filteredPressure = dataType === 'resep' || dataType === 'ai' ? [] : pressure;
  const maxPressure = Math.max(...(filteredPressure.map((v) => v.value)), 21);
  const pressureWarn = filteredPressure.some((p) => p.value < 10 || p.value > 21);

  const onDownload = async () => { setToast('Menyiapkan laporan...'); await new Promise((r) => setTimeout(r, 600)); setModal('preview'); };
  const generatePreview = () => window.print();
  const onBooking = form.handleSubmit((values) => { localStorage.setItem('prime-booking-report', JSON.stringify(values)); setModal(null); setToast('Booking pemeriksaan berhasil dibuat.'); navigate('/beranda'); });

  const visionText = useMemo(() => filteredVision.map((v) => `${v.month}: kanan ${v.rightEye}, kiri ${v.leftEye}`).join('; '), [filteredVision]);
  if (loading) return <section className='space-y-4 pb-[120px]'>{Array.from({ length: 5 }).map((_, i) => <LoadingSkeleton key={i} />)}</section>;
  if (error) return <ErrorState message={error} onRetry={() => setError('')} />;

  return <section className="space-y-4 pb-[calc(128px+env(safe-area-inset-bottom))]">
    <Card><div className="flex justify-between gap-3"><div><h1 className="text-2xl font-extrabold">Laporan Kesehatan Mata</h1><p className="text-sm text-prime-black/70">Pantau kondisi mata Anda secara terstruktur dan mudah dibaca.</p></div><button aria-label='Unduh laporan' onClick={onDownload} className='rounded-xl bg-prime-cream p-3'><Download size={18}/></button></div></Card>
    <Card className='bg-gradient-to-br from-[#2a2520] to-[#8f7626] text-white'><p className='flex items-center gap-2 text-sm'><CircleAlert size={16}/>Status Kesehatan Mata: {report.healthStatus}</p><p className='mt-2 text-sm'>Hasil terakhir menunjukkan visus mata kiri lebih rendah dan perlu pemantauan berkala.</p><div className='mt-3 grid grid-cols-2 gap-2 text-xs'><p>Kunjungan: {report.lastVisitDate}</p><p>Dokter: {report.doctorName}</p><p>RM: {report.medicalRecordNumber}</p><p>Status laporan: Aktif</p></div><button onClick={onDownload} className='mt-4 min-h-[44px] rounded-xl bg-white px-4 text-prime-black'>Unduh Laporan</button></Card>
    <div className='grid grid-cols-2 gap-3'>{[['Visus Mata Kanan', report.rightVision, 'Ketajaman penglihatan', 'Normal'], ['Visus Mata Kiri', report.leftVision, 'Ketajaman penglihatan', 'Perlu kontrol'], ['Tekanan Intraokular', `${report.intraocularPressure} mmHg`, 'Tekanan bola mata', 'Dalam batas aman'], ['Risiko Mata Kering', report.dryEyeRisk, 'Kemungkinan keluhan mata kering berdasarkan gejala', 'Pantau gejala']].map((m) => <button key={m[0]} onClick={() => { setSelected(m); setModal('metric'); }} className='min-h-[120px] rounded-2xl bg-white p-3 text-left shadow-sm'><p className='text-xs text-prime-black/60'>{m[0]}</p><p className='text-lg font-bold'>{m[1]}</p><p className='text-xs'>{m[3]}</p><span className='mt-1 inline-flex items-center gap-1 text-[11px] text-prime-black/65'><Info size={12}/>{m[2]}</span></button>)}</div>
    <Card><h2 className='text-lg font-bold'>Filter Laporan</h2><div className='mt-2 flex flex-wrap gap-2'>{periods.map((p)=><button key={p.key} onClick={()=>setPeriod(p.key)} className={`min-h-[44px] rounded-xl px-3 text-xs ${period===p.key?'bg-prime-gold text-white':'bg-prime-cream'}`}>{p.label}</button>)}</div><div className='mt-2 flex flex-wrap gap-2'>{dataTypes.map((p)=><button key={p.key} onClick={()=>setDataType(p.key)} className={`min-h-[44px] rounded-xl px-3 text-xs ${dataType===p.key?'bg-prime-black text-white':'bg-prime-cream'}`}>{p.label}</button>)}</div></Card>
    <Card><h2 className='text-lg font-bold'>Grafik Perkembangan Visus</h2><p className='text-sm text-prime-black/70'>Perbandingan hasil pemeriksaan mata kanan dan kiri dari waktu ke waktu.</p>{filteredVision.length===0?<EmptyState message='Belum ada data pemeriksaan pada periode ini.'/>:<div className='mt-3 rounded-2xl bg-[#fffaf0] p-3'><div className='grid grid-cols-3 gap-2 text-xs'>{filteredVision.map((v)=><button key={v.date} onClick={()=>{setSelected(v);setModal('vision')}} className='rounded-xl bg-white p-2'><p>{v.month}</p><p>K {v.rightEye}</p><p>Ki {v.leftEye}</p></button>)}</div><p className='mt-2 text-xs'>Ringkasan: {visionText}</p></div>}</Card>
    <Card><div className='flex items-center justify-between'><h2 className='text-lg font-bold'>Tekanan Intraokular</h2><span className='rounded-full bg-prime-cream px-3 py-1 text-xs'>Dalam batas aman</span></div><p className='text-sm text-prime-black/70'>Tekanan bola mata dipantau untuk membantu deteksi risiko glaukoma.</p>{filteredPressure.length===0?<EmptyState message='Belum ada data tekanan intraokular pada periode ini.'/>:<div className='mt-3 flex items-end gap-2 rounded-2xl bg-[#fffaf0] p-3 min-h-[170px]'>{filteredPressure.map((b)=><button key={b.month} onClick={()=>{setSelected(b);setModal('pressure')}} className='flex flex-1 flex-col items-center'><span className='text-[10px]'>{b.value}</span><div className='w-full rounded-t-lg bg-prime-gold' style={{height:`${(b.value/maxPressure)*100}px`}}/><p className='text-xs'>{b.month}</p></button>)}</div>}{pressureWarn && <p className='mt-2 text-sm text-amber-700'>Tekanan intraokular perlu evaluasi dokter.</p>}</Card>
    <Card><h2 className='text-lg font-bold'>Riwayat Pemeriksaan</h2>{filteredHistory.length===0?<EmptyState message='Belum ada riwayat pemeriksaan.'/>:filteredHistory.map((h)=><button key={h.id} onClick={()=>{setSelected(h);setModal('history')}} className='mt-2 flex w-full items-center rounded-xl bg-prime-cream/30 p-3 text-left'><div className='flex-1'><p className='text-xs'>{h.date}</p><p className='font-semibold'>{h.title}</p><p className='text-xs'>{h.doctor} • {h.status}</p></div><ChevronRight size={16}/></button>)}</Card>
    <Card><h2 className='text-lg font-bold'>Hasil AI Mata Terakhir</h2><p className='text-sm'>{lastAi.date} • Risiko {lastAi.riskLevel} • Keluhan {lastAi.symptoms[0]}</p><button onClick={()=>setModal('ai')} className='mt-3 min-h-[44px] w-full rounded-xl bg-prime-black text-white'>Lihat Detail AI</button></Card>
    <Card><h2 className='text-lg font-bold'>Rekomendasi</h2><p className='text-sm'>Lakukan pemeriksaan ulang 1 bulan lagi atau lebih cepat jika keluhan bertambah.</p><div className='mt-3 grid grid-cols-2 gap-2'><button onClick={()=>setModal('booking')} className='min-h-[44px] rounded-xl bg-prime-gold text-white'>Booking Pemeriksaan</button><a href='https://wa.me/6281234567890' className='min-h-[44px] rounded-xl bg-prime-cream inline-flex items-center justify-center gap-2'><PhoneCall size={14}/>Hubungi Klinik</a></div></Card>

    {modal==='metric' && <Modal title='Penjelasan Metric' onClose={()=>setModal(null)}><p className='text-sm'>{selected?.[2]}</p></Modal>}
    {modal==='vision' && <Modal title='Detail Titik Visus' onClose={()=>setModal(null)}><p className='text-sm'>{selected?.date} • Kanan {selected?.rightEye} • Kiri {selected?.leftEye}</p></Modal>}
    {modal==='pressure' && <Modal title='Detail Tekanan' onClose={()=>setModal(null)}><p className='text-sm'>{selected?.month}: {selected?.value} mmHg</p></Modal>}
    {modal==='history' && <Modal title='Detail Pemeriksaan' onClose={()=>setModal(null)}><div className='space-y-1 text-sm'><p>Tanggal: {selected?.date}</p><p>Jenis: {selected?.title}</p><p>Keluhan: {selected?.complaint}</p><p>Visus: {selected?.rightVision}/{selected?.leftVision}</p><p>TIO: {selected?.intraocularPressure} mmHg</p><p>Diagnosis: {selected?.diagnosis}</p><button onClick={onDownload} className='mt-2 rounded-lg bg-prime-cream px-3 py-2'>Unduh detail</button></div></Modal>}
    {modal==='ai' && <Modal title='Detail AI' onClose={()=>setModal(null)}><div className='space-y-1 text-sm'><p>Keluhan: {lastAi.symptoms.join(', ')}</p><p>Durasi: {lastAi.duration}</p><p>Tingkat nyeri: {lastAi.painLevel}/10</p><p>Alasan analisis: {lastAi.analysisReason}</p><p>Rekomendasi: {lastAi.recommendation}</p><p className='rounded-xl bg-prime-cream/40 p-2 text-xs'>AI bukan diagnosis dokter.</p></div></Modal>}
    {modal==='booking' && <Modal title='Booking Pemeriksaan' onClose={()=>setModal(null)}><form onSubmit={onBooking} className='space-y-2 text-sm'><input aria-label='Jenis pemeriksaan' {...form.register('examType')} className='w-full rounded-lg border p-2'/><input type='date' aria-label='Tanggal' {...form.register('date')} className='w-full rounded-lg border p-2'/><input type='time' aria-label='Jam' {...form.register('time')} className='w-full rounded-lg border p-2'/><input aria-label='Keluhan singkat' {...form.register('complaint')} className='w-full rounded-lg border p-2'/><input aria-label='Nomor WhatsApp' {...form.register('whatsapp')} className='w-full rounded-lg border p-2'/><button className='min-h-[44px] w-full rounded-xl bg-prime-gold text-white'>Konfirmasi booking</button></form></Modal>}
    {modal==='preview' && <Modal title='Preview Laporan' onClose={()=>setModal(null)}><div className='space-y-1 text-sm'><p>Pasien: {report.patientName}</p><p>RM: {report.medicalRecordNumber}</p><p>Dokter: {report.doctorName}</p><p>Visus: {report.rightVision} / {report.leftVision}</p><p>TIO: {report.intraocularPressure} mmHg</p><p>Risiko mata kering: {report.dryEyeRisk}</p><p>Hasil AI: {lastAi.summary}</p><p>Rekomendasi: Kontrol 1 bulan lagi.</p><div className='grid grid-cols-3 gap-2 pt-2'><button onClick={()=>{generatePreview();setToast('Laporan berhasil diunduh.');}} className='rounded-lg bg-prime-gold px-2 py-2 text-white'>Unduh PDF</button><button onClick={()=>setToast('Fitur bagikan diproses.')} className='rounded-lg bg-prime-cream px-2 py-2'>Bagikan</button><button onClick={()=>setModal(null)} className='rounded-lg bg-prime-black px-2 py-2 text-white'>Tutup</button></div></div></Modal>}
    {toast && <Toast text={toast}/>} 
  </section>;
}
